### ISSUE TITLE
Sdk not integrate with the new version(1.0.1) 

### ISSUE THREAD

**Issue by Abhinandan-Chada** [voxeet/android-sdk-sample#1]
I update my application with new version of voxeet(1.0.1),but when ever i compile the code some of the file are missing and create compile issue .Here is the attached screen shot of the issue:

(https://user-images.githubusercontent.com/8521697/40312398-69263140-5d30-11e8-9561-6a6be62cc5f2.png)

I just change the gradle file lines.Here is the attached screenshot:

(https://user-images.githubusercontent.com/8521697/40312582-d5d60900-5d30-11e8-84ca-7606554a1b27.png)

But if i compile the code with the older version it works fine .All methods and classes are compiled and provide the actual output of the application.

I am using Android Studio 3.1.2 and gradle 4.1 version.

**Comment by codlab** [comment]
Your current gradle is using the sdk and not the toolkit sdk (as stated in the README.md)

Please use : 

```
dependencies {
  compile ('com.voxeet.sdk:toolkit:1.0') {
    transitive = true
  }
}
```
